import React from "react"
import { Container } from "semantic-ui-react"
import Header from "./Header"
import Head from "next/head"

const Layout = (props) => {
  return (
    <Container>
      <Head>
        <title>CrowdCoin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {props.children}
    </Container>
  )
}

export default Layout
